# Generated by Django 3.2.4 on 2021-08-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('dommaine', models.CharField(max_length=254)),
                ('logo', models.ImageField(null=True, upload_to='uploads')),
                ('description', models.CharField(max_length=254)),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ItWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('dommaine', models.CharField(choices=[('1', 'developement web'), ('2', 'art grafique'), ('3', 'developement mobile'), ('4', 'cybersecuriter')], max_length=254, null=True)),
                ('competence', models.CharField(max_length=254)),
                ('sexe', models.CharField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads')),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=254, null=True)),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('numero_telephone', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dommaine', models.CharField(choices=[('1', 'developement web'), ('2', 'art grafique'), ('3', 'developement mobile'), ('4', 'cybersecuriter')], max_length=254, null=True)),
                ('intituler', models.CharField(max_length=254, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('description', models.CharField(max_length=254, null=True)),
                ('fourcette_prix', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('outils', models.TextField()),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.entrepriseparticulier')),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.TextField(null=True)),
                ('decription', models.TextField(null=True)),
                ('date_postula', models.DateTimeField()),
                ('itworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.itworker')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.mission')),
            ],
        ),
    ]
