# Generated by Django 4.0 on 2022-06-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('logo', models.ImageField(null=True, upload_to='uploadslogo')),
                ('description', models.CharField(max_length=254)),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('domaine', models.CharField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=254, null=True)),
                ('competence', models.CharField(max_length=254)),
                ('sexe', models.CharField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads')),
                ('date_naissance', models.DateField(null=True)),
                ('description', models.CharField(max_length=254, null=True)),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('numero_telephone', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=254, null=True)),
                ('domaine', models.CharField(max_length=254, null=True)),
                ('intituler', models.CharField(max_length=254, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateField(null=True)),
                ('description', models.TextField()),
                ('fourcette_prix', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('outils', models.CharField(max_length=254, null=True)),
                ('isPosted', models.BooleanField(default=False)),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.entrepriseparticulier')),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(null=True)),
                ('date_postula', models.DateTimeField(auto_now_add=True)),
                ('itworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.itworker')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_it.mission')),
            ],
        ),
    ]
