# Generated by Django 3.2.6 on 2021-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuler',
            name='a_poster',
            field=models.BooleanField(default=False),
        ),
    ]
