# Generated by Django 3.2.4 on 2021-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0002_alter_itworker_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepriseparticulier',
            name='domaine',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
