# Generated by Django 3.2.6 on 2021-08-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0002_postuler_a_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='isPosted',
        ),
    ]
