# Generated by Django 3.2.6 on 2021-08-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0003_remove_mission_isposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuler',
            name='a_poster',
        ),
        migrations.AddField(
            model_name='mission',
            name='isPosted',
            field=models.BooleanField(default=False),
        ),
    ]
