# Generated by Django 3.2.6 on 2021-08-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0004_auto_20210822_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='outils',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
