# Generated by Django 3.2.4 on 2021-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0005_alter_postuler_date_postula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postuler',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='postuler',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
