# Generated by Django 3.2.6 on 2021-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0005_auto_20210824_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepriseparticulier',
            name='domaine',
            field=models.CharField(choices=[('1', 'developement web'), ('2', 'art grafique'), ('3', 'developement mobile'), ('4', 'Experte en sécurité informatique'), ('5', 'developpeur full-stack'), ('6', 'Développeur back-end'), ('7', 'Ingénieur DevOps'), ('8', 'Architecte réseau'), ('9', 'Architecte informatique'), ('10', 'Testeur'), ('11', 'Développeur de jeux vidéo'), ('12', 'Infographiste')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itworker',
            name='domaine',
            field=models.CharField(choices=[('1', 'developement web'), ('2', 'art grafique'), ('3', 'developement mobile'), ('4', 'Experte en sécurité informatique'), ('5', 'developpeur full-stack'), ('6', 'Développeur back-end'), ('7', 'Ingénieur DevOps'), ('8', 'Architecte réseau'), ('9', 'Architecte informatique'), ('10', 'Testeur'), ('11', 'Développeur de jeux vidéo'), ('12', 'Infographiste')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='domaine',
            field=models.CharField(choices=[('1', 'developement web'), ('2', 'art grafique'), ('3', 'developement mobile'), ('4', 'Experte en sécurité informatique'), ('5', 'developpeur full-stack'), ('6', 'Développeur back-end'), ('7', 'Ingénieur DevOps'), ('8', 'Architecte réseau'), ('9', 'Architecte informatique'), ('10', 'Testeur'), ('11', 'Développeur de jeux vidéo'), ('12', 'Infographiste')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='outils',
            field=models.CharField(choices=[('1', 'CMS'), ('2', 'Jquery'), ('3', 'php'), ('4', 'Django'), ('5', 'laravel'), ('6', 'java'), ('7', 'Javascript'), ('8', 'Angular'), ('9', 'Python'), ('10', 'c'), ('11', 'SQL'), ('12', 'NOSQL')], max_length=254, null=True),
        ),
    ]
