# Generated by Django 3.2.6 on 2021-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0006_auto_20210830_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepriseparticulier',
            name='domaine',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itworker',
            name='domaine',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='domaine',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='outils',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
