# Generated by Django 3.2.4 on 2021-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0006_auto_20210811_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='logo',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='domaine',
            field=models.CharField(choices=[('developement web', 'developement web'), ('art grafique', 'art grafique'), ('developement mobile', 'developement mobile'), ('cybersecuriter', 'cybersecuriter')], max_length=254, null=True),
        ),
    ]
